/**
 * Single source of truth for Figma command names, shared by:
 *  - the MCP server (FigmaCommand type for sendCommandToFigma)
 *  - the relay (validation: parentId requirements, blocked commands)
 *  - the relay tests (so they exercise the real lists, not a hand-copied mirror)
 *
 * The plugin (code.js) is plain JS and keeps its own switch; when adding a
 * command, add it HERE and in code.js's handleCommand.
 */

/** Stateful commands the relay refuses unconditionally (page-context conflicts). */
export const BLOCKED_COMMANDS = ["set_current_page"] as const;

/** Creation commands that ALWAYS require parentId (no implicit page-context dependency). */
export const CREATION_COMMANDS = [
  "create_rectangle",
  "create_frame",
  "create_text",
  "create_ellipse",
  "create_polygon",
  "create_star",
  "create_vector",
  "create_line",
  "create_component_instance",
  "create_component_set",
  "set_svg",
  "clone_node",
  "create_component_from_node",
  // FigJam creation commands
  "create_section",
  "create_sticky",
  "create_shape_with_text",
  "create_connector",
] as const;

/** Every command the MCP server can send to the plugin (plus relay-level join/ping). */
export const FIGMA_COMMANDS = [
  "get_document_info",
  "get_selection",
  "get_node_info",
  "get_nodes_info",
  "create_rectangle",
  "create_frame",
  "create_text",
  "create_ellipse",
  "create_polygon",
  "create_star",
  "create_vector",
  "create_line",
  "set_fill_color",
  "set_stroke_color",
  "move_node",
  "resize_node",
  "delete_node",
  "get_styles",
  "get_local_components",
  "create_component_instance",
  "export_node_as_image",
  "get_visual_snapshot",
  "batch_operations",
  "get_css",
  "get_fonts_used",
  "scan_assets",
  "get_asset",
  "extract_asset",
  "classify_asset",
  "join",
  "ping",
  "set_corner_radius",
  "clone_node",
  "set_text_content",
  "scan_text_nodes",
  "set_multiple_text_contents",
  "set_auto_layout",
  "set_font_name",
  "set_font_size",
  "set_font_weight",
  "set_letter_spacing",
  "set_line_height",
  "set_paragraph_spacing",
  "set_text_case",
  "set_text_decoration",
  "set_text_align",
  "get_styled_text_segments",
  "load_font_async",
  "get_remote_components",
  "set_effects",
  "set_effect_style_id",
  "set_text_style_id",
  "group_nodes",
  "ungroup_nodes",
  "flatten_node",
  "insert_child",
  "create_component_from_node",
  "create_component_set",
  "set_instance_variant",
  "set_reactions",
  "get_reactions",
  "detach_instance",
  "create_page",
  "delete_page",
  "rename_page",
  "get_pages",
  "set_current_page",
  "rename_node",
  "set_selection_colors",
  "set_image_fill",
  "get_image_from_node",
  "replace_image_fill",
  "apply_image_transform",
  "set_image_filters",
  "rotate_node",
  "set_node_properties",
  "reorder_node",
  "duplicate_page",
  "convert_to_frame",
  "set_gradient",
  "boolean_operation",
  "set_svg",
  "get_svg",
  "set_image",
  "set_grid",
  "get_grid",
  "set_guide",
  "get_guide",
  "set_annotation",
  "get_annotation",
  "create_text_style",
  "create_paint_style",
  "create_effect_style",
  "get_variables",
  "set_variable",
  "apply_variable_to_node",
  "switch_variable_mode",
  "get_figjam_elements",
  "create_sticky",
  "set_sticky_text",
  "create_shape_with_text",
  "create_connector",
  "create_section",
] as const;

export type FigmaCommand = (typeof FIGMA_COMMANDS)[number];
